package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildWebsites'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildWebsites")) {
    vcs {

        check(checkoutMode == CheckoutMode.AUTO) {
            "Unexpected option value: checkoutMode = $checkoutMode"
        }
        checkoutMode = CheckoutMode.ON_SERVER
    }
}
