package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.FinishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndPushDockerContainers'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndPushDockerContainers")) {
    triggers {
        val trigger1 = find<FinishBuildTrigger> {
            finishBuildTrigger {
                buildType = "MnMdeEdfi_BuildWebsites"
                successfulOnly = true
                branchFilter = "+:*"
            }
        }
        trigger1.apply {

            buildParams {
                param("PackageVersion", "%PackageVersion%")
                text("TrunkName", "%TrunkName%", allowEmpty = true)
                param("teamcity.build.branch", "%teamcity.build.branch%")
            }
        }
    }

    dependencies {
        expect(RelativeId("BuildWebsites")) {
            snapshot {
            }

            artifacts {
                cleanDestination = true
                artifactRules = """+:* => Ed-Fi-ODS-Implementation\packages"""
            }
        }
        update(RelativeId("BuildWebsites")) {
            artifacts {
                cleanDestination = true
                artifactRules = """+:* => Ed-Fi-ODS-Implementation\packages"""
            }
        }

    }
}
