package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.FinishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndPushDockerContainers'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndPushDockerContainers")) {
    vcs {

        check(checkoutMode == CheckoutMode.AUTO) {
            "Unexpected option value: checkoutMode = $checkoutMode"
        }
        checkoutMode = CheckoutMode.ON_SERVER
    }

    triggers {
        val trigger1 = find<FinishBuildTrigger> {
            finishBuildTrigger {
                buildType = "MnMdeEdfi_BuildWebsites"
                successfulOnly = true
                branchFilter = "+:*"
            }
        }
        trigger1.apply {

            buildParams {
                text("TrunkName", "%dep.MnMdeEdfi_BuildWebsites.teamcity.build.branch%", allowEmpty = true)
            }
        }
    }
}
