package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            param("nexus.docker.feed", "http://edu-dockeru01.educ.state.mn.us:8081/repository/edfi-docker/")
        }
        update {
            param("nexus.docker.feed", "%mn-mde-edfi.nexus.host%/repository/edfi-docker/")
        }
        expect {
            param("nexus.nuget.api.key", "7a7a0676-447f-39a2-87a9-6fbb251794de ")
        }
        update {
            param("nexus.nuget.api.key", "%mn-mde-edfi.nexus.nuget.apikey%")
        }
        expect {
            param("nexus.nuget.package.source", "http://edu-dockeru01.educ.state.mn.us:8081/repository/Ed-Fi/")
        }
        update {
            param("nexus.nuget.package.source", "%mn-mde-edfi.nexus.host%/repository/Ed-Fi/")
        }
        expect {
            param("octopus.nuget.apikey", "API-VOYBXBWTTZSUKVD6QPEAMLCF2VGLRXTF")
        }
        update {
            param("octopus.nuget.apikey", "%OctopusAPIKey%")
        }
    }

    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_2"
                name = "Nexus"
                url = "http://edu-dockeru01.educ.state.mn.us:8081/repository/EdFi-Docker/"
                userName = "EdFi-Admin"
                password = "zxxeb6303fcd39ad33fdf804aa6e65315f5"
            }
        }
        feature1.apply {
            password = "credentialsJSON:af64153b-959a-4cf6-ae87-8a04392392d9"
        }
    }
}
