package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComMnMdeEdfiEdFiOdsRefsHeadsDevelopMnV31'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComMnMdeEdfiEdFiOdsRefsHeadsDevelopMnV31")
    name = "https://github.com/mn-mde-edfi/Ed-Fi-ODS#refs/heads/develop-MN-v31"
    url = "https://github.com/mn-mde-edfi/Ed-Fi-ODS"
    branch = "refs/heads/develop-MN-v31"
    authMethod = password {
        userName = "dennispiatt"
        password = "credentialsJSON:0f12473a-0eb1-4d19-b397-866c46491400"
    }
}))

