package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.SvnVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'KeyretrievalV52'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("KeyretrievalV52")) {
    val expected = SvnVcsRoot({
        id("KeyretrievalV52")
        name = "keyretrieval-v52"
        url = "http://192.168.0.62:8280/svn/mndoe/trunk/keyretrival-v52/"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as SvnVcsRoot).apply {
        url = "http://mn-doe-svn-1/svn/mndoe/trunk/keyretrival-v52/"
    }

}
